package-lock.json, package.json
`path` is included in nodejs (just like `fs`), and does not need to be brought in as an external dep. Removing!
=> fix: drop unneeded path dependency

lib/index.ts, lib/parsers/index.ts, package-lock.json, package.json, test/fixtures/dotnet-core-simple-project/expected-tree.json, test/fixtures/dotnet-core-simple-project/simple-project.csproj, test/fixtures/dotnet-simple-project-with-devDeps/expected-tree-from-csproj-without-dev.json, test/fixtures/dotnet-simple-project-with-devDeps/expected-tree-from-csproj.json, test/fixtures/dotnet-simple-project-with-devDeps/simple-project-with-dev.csproj, test/lib/index.ts
- Start saving more deps that are definedin `*.csproj` files in format:
```
<Reference Include="Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
<HintPath>..\packages\Newtonsoft.Json.10.0.3\lib\net45\Newtonsoft.Json.dll</HintPath
</Reference>
```
and 
```   
<Reference Include="System.Web.ApplicationServices" />
```
- Added some tests
Note: dependency Type is for now assumed prod until we determine correct way to tell it is a dev dep
=> feat: start reading the Reference Include property

lib/index.ts, test/fixtures/dotnet-fs-simple-project/expected-tree.json, test/fixtures/dotnet-fs-simple-project/manifest.fsproj, test/lib/index.ts
Currently we can parse `packages.config`, `.csproj` or `.vbproj`. But `.fsproj` files is identical to `.csproj`.
This PR adds:
- `.fsproj` to available extensions list
- test for generic F# project
https://snyksec.atlassian.net/browse/SC-6470
=> feat: added .fsproj support

lib/errors/index.ts, lib/errors/invalid-user-input-error.ts, lib/index.ts, lib/parsers/index.ts, test/lib/dependencies.test.ts
Parser will now send InvalidUserInputError when failing on invalid files, instead of sending 500 error
=> feat: send InvalidUserInputError for invalid files

lib/parsers/index.ts, test/fixtures/dotnet-core-simple-project/simple-project.csproj, test/lib/dependencies.test.ts, test/lib/target-frameworks.test.ts
- Add missing support for `targetFrameworkVersion` property which is the same as `targetFramework`
- Split out `targetFramework` from `targetFrameworks`:  
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#implicit-package-references
We use `targetFramework` for 1 and `targetFrameworks` for multiple
Looks like for `targetFrameworkVersion` it is always 1 https://www.cyotek.com/blog/targeting-multiple-versions-of-the-net-framework-from-the-same-project
https://snyksec.atlassian.net/browse/BST-241
=> fix: Support for targetFramework and targetFrameworkVersion

lib/index.ts, lib/parsers/index.ts, test/fixtures/dotnet-multiple-target-frameworks/packages.config, test/lib/target-frameworks.test.ts
Adds packages.config support for targetFramework extraction.
[https://snyksec.atlassian.net/browse/BST-265](https://snyksec.atlassian.net/browse/BST-265)
=> feat: adds packages.config support for target framework parsing.

lib/index.ts
Added missing export `extractTargetFrameworksFromProjectConfig`.
https://snyksec.atlassian.net/browse/BST-272
=> fix: added missing export `extractTargetFrameworksFromProjectConfig`

lib/parsers/index.ts, test/fixtures/dotnet-core-variable-version/expected-tree.json, test/fixtures/dotnet-core-variable-version/manifest.csproj, test/lib/dependencies.test.ts
I found a project in the wild that shows you can use variables in the XML for versions just like in Maven,
here is an implementation for this for .proj files only.
Check the fixture
Run the tests
=> feat: Support for package version set as xml variables

lib/index.ts, lib/parsers/index.ts, test/fixtures/dotnet-movie-hunter-api/expected-tree.json, test/fixtures/dotnet-multiple-target-frameworks/expected-tree-net46.json, test/fixtures/dotnet-multiple-target-frameworks/packages.config, test/fixtures/dotnet-simple-project-with-devDeps/expected-tree-without-dev.json, test/fixtures/dotnet-simple-project-with-devDeps/expected-tree.json, test/fixtures/dotnet-simple-project/expected-tree.json, test/lib/dependencies.test.ts
Allows filtering dependencies in `packages.config` file per their targetFramework specification.
=> Get deptree for target framework

lib/index.ts, test/fixtures/dotnet-no-packagereference/project.csproj, test/fixtures/dotnet-no-packagereference/project.fsproj, test/fixtures/dotnet-no-packagereference/project.vbproj, test/lib/package-reference.test.ts
Adds function to assert whether a project file contains any `PackageReference` 
(Quoted from the ticket)
In order to understand correctly, which file should be used to get dependency tree, we need to know if user have migrated to the new version of dependency management. We can recognise it by the presence of at least one `<PackageReference>` node in `*.[cfsvb]proj`.
https://snyksec.atlassian.net/browse/BST-315
=> Feat: Function to assert whether manifest file contains PackageReference

lib/parsers/index.ts, test/lib/target-frameworks.test.ts
Fixes parsing of `<TargetFrameworkVersion>`
=> fix: resolve <TargetFrameworkVersion> properly

lib/parsers/index.ts
Some customer projects have the Update property instead of Include, which we currently don't handle and results in errors in generating the dependency graph.
This PR fixes this problem so that dependency names are correctly pulled from the Update property.
https://snyk.zendesk.com/agent/tickets/1315
=> fix: handle Update property in project references

lib/parsers/index.ts, test/fixtures/dotnet-fs-package-reference-update/example.fsproj, test/fixtures/dotnet-fs-package-reference-update/expected-tree.json, test/lib/dependencies.test.ts
Gracefully handle <PackageReference Update="">, we were returning undefined deps
and this fails import.
Also added to support for multi-groups, <ItemGroups> can be defined many times and
according to the docs it is all the same together or separately.
We were only grabbing the first group.
https://docs.microsoft.com/en-us/dotnet/core/tools/dependencies
`<PackageReference Update>` syntax was not safely handled.
BST-879
=> fix: skip reference update deps

lib/index.ts, lib/parsers/index.ts, test/fixtures/dotnet-no-packagereference/Packages.props, test/fixtures/dotnet-no-packagereference/project.csproj, test/fixtures/dotnet-variables-resolved/Steeltoe.Extensions.Configuration.CloudFoundryAutofac.Test.csproj, test/lib/variables.test.ts
- resolve trees in full when variables are mapped from `props` files and used as a lookup map
=> Feat: use props map when resolving

lib/index.ts, lib/parsers/index.ts, lib/parsers/project-assets-json-parser.ts, package.json
Use forked non-vulnerable `@snyk/lodash` instead of `lodash`
=> feat: patch vulnerable lodash using @snyk/lodash

package.json
`@types` packages are only needed at compile time. `typescript` is a `devDependency`, so I'm reasonably sure we're not compiling with only prod deps installed, so this can definitely be a `devDependency`.
Aiming to reduce bundle size for `snyk/snyk`.
=> feat: @types is not a production dependency

.travis.yml, appveyor.yml, lib/index.ts, lib/parsers/index.ts, lib/parsers/project-assets-json-parser.ts, package.json, tsconfig.json
This is a heavy-handed attempt to migrate away from `lodash`, and use language features where possible. It's mostly find/replace.
Moving to `node 8`, is a `BREAKING CHANGE`.
=> fix: lodash 'dot' packages, where necessary

lib/parsers/index.ts, test/fixtures/dotnet-multiple-target-frameworks/multi-target.csproj, test/lib/target-frameworks.test.ts
Due to the way the string split function is working, the string split produces 3 items (['netstandard2.0','net462','']) from this string: <netstandard2.0;net462;> and not two. 
The Test
This was reported by a customer 
Note that there will be another PR for the dotnet-deps project once this one is resolved
https://snyk.zendesk.com/agent/tickets/7939
=> fix: correcting a bug that generates a third blank target framework

jest.config.js, lib/parsers/index.ts, package.json, test/lib/index.spec.ts
This pr ignores the empty PropertyGroup tags when importing the project instead of throwing an error and stopping you from importing the project into Snyk.
Import a project with empty PropertyGroup tag;
<PropertyGroup>
</PropertyGroup>
If this is imported then it should not fail like it did previously when this was empty. 
Previously the following error would appear; 
https://snyksec.atlassian.net/secure/RapidBoard.jspa?rapidView=248&projectKey=LOKI&modal=detail&selectedIssue=LOKI-114
=> fixed import error when tag is empty for dotnet projects

lib/parsers/index.ts, test/fixtures/dotnet-conditional-frameworks/expected-tree.json, test/fixtures/dotnet-core-simple-project/expected-tree.json, test/fixtures/dotnet-simple-project-with-devDeps/expected-tree-from-csproj-without-dev.json, test/fixtures/dotnet-simple-project-with-devDeps/expected-tree-from-csproj.json, test/fixtures/dotnet-vb-simple-project/expected-tree.json, test/fixtures/reference-assemblies-with-package-reference/project.csproj, test/fixtures/reference-assemblies/project.csproj, test/lib/buildDepTreeFromProjectFile.spec.ts, test/lib/dependencies.test.ts, test/lib/index.spec.ts, test/lib/variables.test.ts
Drop support for [reference assemblies](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies) in dependency tree creation for project files. Reference assemblies are sourced from local machine (such as local `dll` or SDK) and are not downloaded from remote feeds (such as nuget.org). Therefore we cannot provide any level of advice how to fix these packages should they be vulnerable. We also decided not to report such packages altogehter
=> feat: remove support for reference assemblies

.travis.yml
Latest semantic-releases were failing due to outdated node version, see https://app.travis-ci.com/github/snyk/dotnet-deps-parser/jobs/549309091.
Apply minimum required node version for releases
=> feat: trigger release

lib/errors/index.ts, lib/errors/invalid-user-input-error.ts, lib/index.ts, lib/parsers/index.ts, package.json, test/lib/dependencies.spec.ts, test/lib/props.spec.ts, test/lib/target-frameworks.spec.ts
Changed error to be from error-catalog so that they are properly handlled for dotnet-deps.
[Jira ticket OSM-529](https://snyksec.atlassian.net/browse/OSM-529)
Should we also handle unexpected errors?
=> feat: [OSM-529] updated errors to be error-catalog style

lib/index.ts, test/lib/target-frameworks.spec.ts
Currently the logic exists in the `snyk-nuget-plugin` code: https://github.com/snyk/snyk-nuget-plugin/blob/9c48169064bb397acfb2d7b727892fdddc70fb7c/lib/nuget-parser/runtime-assembly.ts#L24-L42
We are moving it here to share it between our internal and external services, and avoid repeating ourselves unnecessarily.
After this merge we're going to remove it from `snyk-nuget-plugin` and add it to our internal service as well.
=> fix: [OSM-699] Adding new `TargetFramework` guard for V2 logic

package.json
Updating `error-catalog` dependency due to some error catalog restructuring and adjusting changed errors accordingly.
=> fix: [OSM-441] Adjusting to reorganized error catalog

lib/parsers/index.ts, test/fixtures/dotnet-empty-property-group/empty-property-group.csproj, test/fixtures/dotnet-empty-property-group/expected-tree.json, test/fixtures/dotnet-empty-property-group/packages.config, test/lib/dependencies.spec.ts, test/lib/target-frameworks.spec.ts
Some users might use propertyGroups like:
```
<PropertyGroup>
</PropertyGroup>
```
This PR adds handling for that case, and returns the usual empty array instead of an error.
=> fix: handle-empty-property-group

lib/index.ts, package.json, test/fixtures/dotnet-core-global-json/global_with_comments.json
Use an actual JSONC parser to parse global.json, as this is the format Microsoft uses, rather than trying to remove comments with a regex. I picked https://www.npmjs.com/package/jsonc-parser as this has 23M weekly downloads, and is well-maintained by Microsoft.
I originally found this issue when trying to import public repo `OrchardCore` which has this global.json:
```json
{
"comment": "We only update the version manually with major SDK updates to keep using any more recent SDK version possible. See https://github.com/OrchardCMS/OrchardCore/pull/17808.",
"sdk": {
"version": "9.0.100",
"rollForward": "latestMajor"
}
}
```
=> feat: [OSM-2902] Parse global.json with a JSONC parser
